import Sidebar from "@/components/shared/sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <Sidebar />
          <Providers>
            <SidebarInset>{children}</SidebarInset>
          </Providers>
          <Toaster
            toastOptions={{
              success: {
                duration: 3000,
                style: { padding: "1rem" },
              },
              error: {
                duration: 3000,
                style: { padding: "1rem" },
              },
              position: "bottom-center",
            }}
          />
        </SidebarProvider>
      </body>
    </html>
  );
}
